Task 5

diff --git a/0x0C-web_server/3-redirection b/0x0C-web_server/3-redirection
--- a/0x0C-web_server/3-redirection
+++ b/0x0C-web_server/3-redirection
@@ -1,5 +1,6 @@
 #!/usr/bin/env bash
-# Install and configure nginx on a web server and  redirects
+# This Scripts configures Nginx on a Web Server
+# Redirects
 
 config_file="/etc/nginx/nginx.conf"
 root_path="/data/www/"
@@ -22,8 +23,14 @@ http {
 		server_name    theegsd.tech www.theegsd.tech;
 		root           $root_path;
 		index          index.html;
+
 		location / {
 			root $root_path;
+
+		}
+
+		location /redirect_me {
+			return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4$request_uri;
 
 		}
 	}
@@ -36,19 +43,22 @@ index_content="Hello World!"
 echo "Installing nginx server..."
 apt-get -y update
 apt-get -y install nginx
-ufw allow 'Nginx HTTP'
+ufw allow "Nginx HTTP"
 
-echo "Creating the web root folder @ $root_path"
+# echo "Creating the web root folder @ $root_path"
 mkdir -p "$root_path"
 echo "$index_content" > "$root_path/index.html"
 
-echo "Adding the configuration file @ $config_file"
+# echo "Adding the configuration file @ $config_file"
 echo "$config_content" > "$config_file"
 
-echo "Hello World!" >  /var/www/html/index.nginx-debian.html
-sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" "$config_file"
 
-echo "Starting the server..."
+# echo "Starting the server..."
 
 service nginx start
 
+if [ "$?" == "0" ]; then
+	echo "Server Started successfully"
+else
+	echo "Unable to start the server for some reason"
+fi
